services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    hostname: yuzu-app
    ports:
      - "5000:5000"
    volumes:
      - .:/project:ro
      - ./storage:/storage
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      - db
    networks:
      - yuzu-net

  db:
    image: mysql:8
    hostname: yuzu-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yuzu_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./storage/db:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./sql/seeder.sql:/docker-entrypoint-initdb.d/seeder.sql:ro
    networks:
      - yuzu-net
  
networks:
  yuzu-net:
    driver: bridge